### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by jensens** [collective/atreal.usersinout#1]
ping @tbenita @tiazma 

Since password export is supported now, a new release would be superior. Also because now many people are starting to rebuild sites in Plone 5 via export/ import.

I can do this too, if you have no resources left.

**Comment by tiazma** [comment]
Hi jensens, 
Actually it would be nice if you could take care of the release, 'cause no resource here :(
You just have been added as Maintainer on pypi.

Thx !
